### ISSUE TITLE
assignment/badsyn4.code should be a badlex instead

### ISSUE THREAD

**Issue by jackdahms** [zqianem/corelang-test-files#2]
```
program
  int i;
begin
  i=1849;
  output i;
end
```

Those are all valid tokens, including the line
`i=1849`
so this should be a lexical error

**Comment by jackdahms** [comment]
So should badsyn5.code, too
```
program
  int i;
begin
  i : = 0;
  output i;
end
```
`i : = 0;` are all valid tokens

**Comment by zqianem** [comment]
Isn't the fact that they are all valid tokens precisely what makes it a syntax error? It would only be a lexical error if they could not be scanned into valid tokens.

**Comment by jackdahms** [comment]
You are 100% correct. I was tired and confused.
